### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by SimonLeclere** [Arcoz0308/arcscord_old#12]
~~a discord package write in typescript~~

A Discord client written in typescript

**Comment by Arcoz0308** [comment]
Oh thx

**Comment by Arcoz0308** [comment]
I fix later 🙂

**Comment by imyanice** [comment]
@SimonLeclere where ??

**Comment by SimonLeclere** [comment]
In the repo's description

**Comment by imyanice** [comment]
Ok ty 😅
