### ISSUE TITLE
Message de rageux 

### ISSUE THREAD

**Issue by lesgoooooo** [Arcoz0308/arcscord_old#13]
**C'est de la merd  arrête sa tou de suitte vraimant c nul `C#
var function c Nul "f(^^*main
nILFJHI C NUL ARRTE T TROP ?BUL SALE MERDE`**

**Comment by Arcoz0308** [comment]
On est sur github, pas sur fornite, donc evite de ragé 🙂

**Comment by AslakOffi** [comment]
hahahaha

**Comment by pauldb09** [comment]
🙄

**Comment by Mystereee** [comment]
Pas les couilles de poster un message avec son vrai compte, obliger d'avoir un double compte.

**Comment by ZoumiSurGithub** [comment]
issou lol rip les lgbts, force à Aslak le non binaire, ça ne doit pas être facile tout les jours pour lui.

**Comment by imyanice** [comment]
Mais whaaat enfaite juste mec si t'es pas content:
1) Tu te tais car tes remarques ne servent a rien,
2) T'as pas de couilles, t'assumes meme pas de poster un message avec ton vrai compte,
3) L'open Source ça sert a faire de ma contribution donc fait une PR :)))))))
@lesgoooooo

**Comment by dannyhpy** [comment]
C'est le feu par ici
